#!/usr/bin/env ruby

require 'rbbt-util'
require 'rbbt/util/simpleopt'

$0 = "rbbt #{$previous_commands*" "} #{ File.basename(__FILE__) }" if $previous_commands

options = SOPT.setup <<EOF

Bootstrap SyntheticRDNA

$ #{$0} [options] <filename.tsv|->

Use - to read from STDIN

-h--help Print this help

EOF
if options[:help]
  if defined? rbbt_usage
    rbbt_usage 
  else
    puts SOPT.doc
  end
  exit 0
end

require 'rbbt/workflow'
Workflow.require_workflow "NEATGenReads"
job = NEATGenReads.example_step(:NEAT_simulate_DNA, "Example")
job.produce
job.recursive_clean

Workflow.require_workflow "SyntheticRDNA"
job = SyntheticRDNA.job(:simulate_sample, "Benchmark", :sample_contigs => 1)
job.produce
job.recursive_clean
